name: dev
channels:
  - pytorch
  - conda-forge
dependencies:
  - python
  - pip
  - jupyterlab
  - jupyterlab-lsp
  - python-language-server
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pyyaml
  - pytorch
  - torchvision
  - cudatoolkit=10.2
